language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2
    
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

after_success:
  - mvn clean test jacoco:report coveralls:report
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { mvn clean deploy --settings .travis/settings.xml -Psign,sonatype -DskipTests=true -B; };"